# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "lrandirene"
repo_name: "prompt_injection_research_daily_arxiv"
show_authors: True
show_links: True
show_badge: False
max_results: 10  # ori: 10 papers, here we first set it to be 1600 to get all previous papers

publish_readme: True
publish_gitpage: False
publish_wechat: False

# file paths
json_readme_path: './docs/safety-arxiv-daily.json'
json_gitpage_path: './docs/safety-arxiv-daily-web.json'
json_wechat_path: './docs/safety-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "LLM Prompt Injection":
        filters: ["prompt injection"]
        required: ["language model", "language models", "LLM", "LLMs"]
        required_2: []
        forbidden: ["MultiModal", "Multi-Modal", "multi-modal", "multimodal", "vision", "audio", "image"]
    "MultiModal Prompt Injection":
        filters: ["prompt injection"]
        required: ["MultiModal", "Multi-Modal", "multi-modal", "multimodal", "vision", "audio", "image"]
        required_2: ["large", "language model", "language models"]
        forbidden: []
